name: Roaya
description: Roaya mobile application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  
  url_launcher: ^5.0.2
  flutter:
    sdk: flutter

  rxdart: ^0.23.1  

  http: 0.12.0+2
  flutter_sparkline: ^0.1.0 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.3.0" 
  font_awesome_flutter: ^8.5.0
  datetime_picker_formfield: ^1.0.0

  simple_animations: ^1.3.4
  fluttertoast: ^3.1.3
  rflutter_alert: ^1.0.3
  google_fonts_arabic: ^1.1.7
  google_fonts: ^0.3.4

  animated_text_kit: ^2.0.0
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/avatar.jpg
    - assets/logo-icon.png
    - assets/dogbackground.png
  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/ElMessiri.woff2
